{{- $gateway := .Values.gateway | default .Values.global.gateway | default dict -}}
{{- $gke := .Values.gke | default .Values.global.gke | default dict -}}
{{- $gkeIap := $gke.iap | default dict -}}
{{- if and $gateway.enabled $gke.enabled -}}
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "simple-charts-common.fullname" . }}
  labels:
    {{- include "simple-charts-common.labels" . | nindent 4 }}
spec:
  default:
    timeoutSec: {{ .Values.timeoutSec}}
    {{ if $gkeIap.enabled }}
    iap:
      enabled: true
      oauth2ClientSecret:
        name: {{ $gkeIap.oauth2ClientSecret}}
      clientID: {{ $gkeIap.clientID}}
    {{ end }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "simple-charts-common.fullname" . }}
{{- end -}}
