{{- $gateway := .Values.gateway | default .Values.global.gateway | default dict -}}
{{- if $gateway.enabled -}}
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "simple-charts-common.fullname" . }}
  labels:
    {{- include "simple-charts-common.labels" . | nindent 4 }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{ $gateway.name }}
    {{- if $gateway.namespace }}
    namespace: {{ $gateway.namespace }}
    {{- end }}
    {{- if $gateway.sectionName }}
    sectionName: {{ $gateway.sectionName }}
    {{- end }}
  hostnames:
  - "{{ include "simple-charts-common.domain" . }}"
  rules:
  - backendRefs:
    - name: {{ include "simple-charts-common.fullname" . }}
      port: {{ .Values.servicePort }}
{{- end -}}
