{{- $gke := .Values.gke | default .Values.global.gke | default dict -}}
{{- if ($gke.managedCertificate | default dict).enabled }}
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ include "simple-charts-common.fullname" . }}
spec:
  domains:
    - {{ include "simple-charts-common.domain" . }}
{{- end }}