{{- $gke := .Values.gke | default .Values.global.gke | default dict -}}
{{- $gkeMonitoring := $gke.monitoring | default dict -}}
{{ if and $gke.enabled $gkeMonitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "simple-charts-common.fullname" . }}
  labels:
    {{- include "simple-charts-common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "simple-charts-common.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ $gkeMonitoring.path | default "/metrics" }}
    interval: {{ $gkeMonitoring.interval | default "30s" }}
{{ end }}
