{{- $fullName := include "simple-app.fullname" . -}}
{{- $labels := include "simple-app.labels" . | nindent 4 -}}

{{ range .Values.volumes }}
{{- if and (not .hostPath) and (not .emptyDir) (and (not .secret) (not .configMap)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- $labels }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}

---
{{ end }}
{{ end }}